name = "novault"
type = "webpack"
account_id = "fd2024a0cea92000209057ebf2cc1ce0"
workers_dev = false
route = "novault.pw/*"
zone_id = "a35d88572bfd8cc99fa9cd48deee28e6"

[site]
bucket = "./dist"
entry-point = "workers-site"
